server:
  port: 9299
  servlet:
    context-path: /es


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm_v1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password:



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml

